name: Test and build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Deps
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck

      - name: Vitest
        run: bun run vitest:run

      - name: Verify Cypress
        env:
          CI: 1
        run: |
          bunx cypress verify
          bunx cypress info
          bunx cypress version
          bunx cypress version --component package
          bunx cypress version --component binary
          bunx cypress version --component electron
          bunx cypress version --component node

      - name: Cypress tests
        run: |
          cd apps/test-app
          bun run test
        env:
          TERM: xterm

      # Save screenshots as test artifacts
      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
