name: Test and build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Deps
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck

      - name: Vitest
        run: bun run vitest:run

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./apps/test-app
          start: npm run dev
          wait-on: http://localhost:3000
